# Generated by Django 2.2.2 on 2019-06-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='innings',
            new_name='inning',
        ),
    ]
